name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [ '1.21' ]

    permissions:
      ## Lint
      contents: read
      # Optional: allow read access to pull request. Use with `only-new-issues` option.
      # pull-requests: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Display Go version
        run: go version

      - name: Build
        run: go build -mod vendor -v ./...
      
      - name: Lint
        uses: golangci/golangci-lint-action@3a919529898de77ec3da873e3063ca4b10e7f5cc #v3
        with:
          version: v1.54

      - name: Test
        run: go test -mod vendor -race -v ./...
  
      - name: Create coverage report
        run: go test -mod vendor -coverprofile=coverage.out -v ./...

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d #v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      # - name: Run GoKart
      #   uses: kitabisa/gokart-action@v1.0.0
      #   with:
      #     globalsTainted: true

      # - name: Upload GoKart results
      #   uses: github/codeql-action/upload-sarif@v1
